# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-13 02:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import grafico.validator


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asignatura',
            fields=[
                ('codasig', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('nomasig', models.CharField(max_length=50)),
                ('creditos', models.DecimalField(decimal_places=0, max_digits=3)),
            ],
            options={
                'db_table': 'asignatura',
            },
        ),
        migrations.CreateModel(
            name='Cursa',
            fields=[
                ('id', models.AutoField(default=-1, primary_key=True, serialize=False)),
                ('trimestre', models.DecimalField(decimal_places=0, max_digits=2)),
                ('estado', models.CharField(max_length=10)),
                ('nota', models.DecimalField(blank=True, decimal_places=0, max_digits=1, null=True)),
            ],
            options={
                'db_table': 'cursa',
            },
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documento', models.FileField(upload_to='', validators=[grafico.validator.validate_file_extension])),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('carnet', models.CharField(max_length=7, primary_key=True, serialize=False)),
                ('cohorte', models.DecimalField(decimal_places=0, max_digits=4)),
                ('carrera', models.DecimalField(decimal_places=0, max_digits=4)),
                ('nombre', models.CharField(max_length=60)),
            ],
            options={
                'db_table': 'estudiante',
            },
        ),
        migrations.AddField(
            model_name='cursa',
            name='carnet',
            field=models.ForeignKey(db_column='carnet', on_delete=django.db.models.deletion.CASCADE, to='grafico.Estudiante'),
        ),
        migrations.AddField(
            model_name='cursa',
            name='codasig',
            field=models.ForeignKey(db_column='codasig', on_delete=django.db.models.deletion.CASCADE, to='grafico.Asignatura'),
        ),
        migrations.AlterUniqueTogether(
            name='cursa',
            unique_together=set([('carnet', 'codasig', 'trimestre')]),
        ),
    ]
