# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-02 02:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grafico', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='carrera',
            field=models.DecimalField(decimal_places=0, default='0800', max_digits=4),
            preserve_default=False,
        ),
    ]
