# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-02 17:29
from __future__ import unicode_literals

from django.db import migrations, models
import grafico.validator


class Migration(migrations.Migration):

    dependencies = [
        ('grafico', '0002_estudiante_carrera'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='documento',
            field=models.FileField(upload_to='', validators=[grafico.validator.validate_file_extension]),
        ),
    ]
