/*
 * Eliminacion de tablas
 */
DROP TABLE CARRERA CASCADE;
DROP TABLE ASIGNATURA CASCADE;
DROP TABLE ESTUDIANTE CASCADE;
DROP TABLE CURSA CASCADE;
DROP TABLE SECCION CASCADE;
DROP TABLE PERTENECE CASCADE;
DROP TABLE PROFESOR CASCADE;
DROP TABLE COORDINACION CASCADE;
DROP TABLE DEPARTAMENTO CASCADE;
DROP TABLE DICTA CASCADE;

